
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app-php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.vite-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - node

  db:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban
      MYSQL_USER: kanban
      MYSQL_PASSWORD: kanban
    #ports:
    #- "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  node:
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=node,nginx,app-nginx
    image: node:20-alpine
    container_name: app-node
    working_dir: /app
    volumes:
      - ./frontend:/app
    # Порт не публикуем наружу!
    expose:
      - "5173"
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  dbdata:
    name: kanbandeck_dbdata
